### ISSUE TITLE
Editorconfig Roslyn errors

### ISSUE THREAD

**Issue by davidhenley** [FoxTes/DesktopClearArchitecture#1]
Is there something I need to do to build this. VS2022 won't build because of Editorconfig errors.

**Comment by FoxTes** [comment]
Hello. Thanks for the comment. I'm using Rider, so I didn't notice this error. I will fix it soon.

**Comment by FoxTes** [comment]
@davidhenley I tried to build a project in VS 2022. It's all right. Could you please show the error?
